name: sentinel_frontend
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
flutter:
  uses-material-design: true
  assets:
    - assets/incident_trace.json