name: 'streaming_content_ads'
version: '1.0.0'
config-version: 2

profile: 'streaming_content_ads'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests_dbt"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  streaming_content_ads:
    +materialized: table